"""New First migration

Revision ID: 12c090efe5b5
Revises: 
Create Date: 2023-08-30 05:32:19.571534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c090efe5b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Publisher',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('author',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_author_Id'), 'author', ['Id'], unique=False)
    op.create_index(op.f('ix_author_Name'), 'author', ['Name'], unique=False)
    op.create_table('book',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(), nullable=True),
    sa.Column('SubTitle', sa.String(), nullable=True),
    sa.Column('PublishDate', sa.Integer(), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Thumbnail', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_book_Id'), 'book', ['Id'], unique=False)
    op.create_table('genres',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_genres_Id'), 'genres', ['Id'], unique=False)
    op.create_index(op.f('ix_genres_Name'), 'genres', ['Name'], unique=False)
    op.create_table('book_author',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.Id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.Id'], )
    )
    op.create_table('book_genre',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.Id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.Id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_genre')
    op.drop_table('book_author')
    op.drop_index(op.f('ix_genres_Name'), table_name='genres')
    op.drop_index(op.f('ix_genres_Id'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_book_Id'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_author_Name'), table_name='author')
    op.drop_index(op.f('ix_author_Id'), table_name='author')
    op.drop_table('author')
    op.drop_table('Publisher')
    # ### end Alembic commands ###
